In the next code cell, you will define a function that computes the least-squares cost function $f(x) = \frac{1}{2}\|y-Ax\|_2^2$ for a given data vector $y \in \mathbb{R}^m$ and  data matrix $A \in \mathbb{R}^{m\times n}$. The inputs of your function is the variable $x \in \mathbb{R}^n$ at which you evaluate your function, as well as the data vector $y$ and the data matrix $A$. The outputs are the function value $f(x)$, the gradient $\nabla f(x)$, and the Hessian matrix $\nabla^2 f(x)$. Don't change any codes other than the lines you are asked to modify.

In [8]:
import numpy as np

def least_squares(x,y,A):
  fval = (1/2) * np.linalg.norm(y-A @ x)**2 #Modify this line so that fval holds the least-squares function value
  grad = -A.T @ (y- A @ x) #Modify this line so that grad holds the gradient vector
  Hessian = A.T @ A #Modify this line so that Hessian holds the Hessian matrix
  return fval, grad, Hessian

# The following codes test your function. I will use different m, n, and random seed to test when grading. So you functions should work for any 
# dimensions of x, y, and A
np.random.seed(42) 
n = 5
m = 50
A = np.random.randn(m,n)
y = np.random.randn(m,1)
x = np.random.randn(n,1)

# Compute function value, gradient, and Hessian by invoking the function least_squares
f, g, H = least_squares(x,y,A)

print(f)
print(g)
print(H)

40.38010572290488
[[-10.44493057]
 [ -6.15842964]
 [ 16.79417156]
 [ 27.83357878]
 [  8.66161788]]
[[ 43.58669391 -13.19266195   1.68633529  -3.08078682  -8.61693048]
 [-13.19266195  41.88555231   4.41469189   1.41527374   2.96584335]
 [  1.68633529   4.41469189  35.09916816  -4.0178838   -2.24011225]
 [ -3.08078682   1.41527374  -4.0178838   43.69295501  -5.01478078]
 [ -8.61693048   2.96584335  -2.24011225  -5.01478078  68.11877429]]


In [10]:
# This cell is for problem 2 because I didn't want to compute if Q is PSD by hand

Q=[[2,2,1],[2,4,1],[1,1,2]]
Q_eigen=np.linalg.eigvalsh(Q)
print(Q_eigen)

[0.65110578 1.60406814 5.74482608]
